// SPDX-License-Identifier: LGPL-2.1-or-later OR GPL-2.0-or-later OR GPL-3.0-or-later OR LicenseRef-ImtCore-Commercial
#pragma once


// ACF includes
#include <icomp/TMakeComponentWrap.h>
#include <icomp/TModelCompWrap.h>

// ImtCore includes (full includes required for TModelCompWrap template instantiation)
#include <imtauthgql/CSimpleLoginWrapComp.h>
#include <imtauthgql/CSimpleLoginComp.h>
#include <imtauthgql/CClientRequestPersonalAccessTokenManagerComp.h>


// forward declarations
namespace imtauthgql
{
class CAuthorizationControllerComp;
class CRoleCollectionControllerComp;
class CUserCollectionControllerComp;
class CUserControllerComp;
class CUserGroupCollectionControllerComp;
class CAuthorizationOptionsControllerComp;
class CSessionControllerComp;
class CClientRequestRemoteSuperuserProviderComp;
class CRemoteSuperuserControllerComp;
class CRemotePermissionCheckerComp;
class CSessionModelObserverComp;
class CSessionModelSubscriberControllerComp;
class CLdapAuthorizationControllerComp;
class CUserSerializableCollectionControllerComp;
class CUserSettingsControllerComp;
class CProfileControllerComp;
class CRoleRemoteCollectionControllerComp;
class CRemoteJwtSessionControllerComp;
class CGqlJwtSessionControllerComp;
class CRoleMetaInfoDelegateComp;
class CUserMetaInfoDelegateComp;
class CGroupMetaInfoDelegateComp;
class CRemoteUserControllerComp;
class CRemoteAuthorizationControllerComp;
class CUserActionCollectionControllerComp;
class CUserActionMetaInfoDelegateComp;
class CClientRequestRoleManagerComp;
class CClientRequestUserManagerComp;
class CClientRequestGroupManagerComp;
class CClientRequestUserInfoProviderComp;
class CClientRequestRoleInfoProviderComp;
class CClientRequestGroupInfoProviderComp;
class CTokenBasedPermissionsProviderComp;
class CPersonalAccessTokenControllerComp;
class CTenantCollectionControllerComp;
class CTenantMetaInfoDelegateComp;
class CTenantCollectionDocumentServiceComp;
class CRemoteProfileControllerComp;
class CJwtSessionControllerProxyComp;
class CRemoteTenantControllerComp;
class CRemoteTenantMembershipManagerControllerComp;
class CTenantManagerControllerComp;
class CTenantMembershipManagerControllerComp;
class CTenantMembershipPublisherComp;
class CRemoteTenantCollectionDocumentServiceControllerComp;
} // namespace imtauthgql


/**
	ImtAuthGqlPck package
*/
namespace ImtAuthGqlPck
{


typedef imtauthgql::CAuthorizationControllerComp AuthorizationController;
typedef imtauthgql::CRoleCollectionControllerComp RoleCollectionController;
typedef imtauthgql::CUserCollectionControllerComp UserCollectionController;
typedef imtauthgql::CUserControllerComp UserController;
typedef imtauthgql::CUserGroupCollectionControllerComp UserGroupCollectionController;
typedef imtauthgql::CAuthorizationOptionsControllerComp AuthorizationOptionsController;
typedef imtauthgql::CSessionControllerComp SessionController;
typedef imtauthgql::CClientRequestRemoteSuperuserProviderComp ClientRequestRemoteSuperuserProvider;
typedef imtauthgql::CRemoteSuperuserControllerComp RemoteSuperuserController;
typedef icomp::TModelCompWrap<imtauthgql::CSimpleLoginWrapComp> SimpleLoginWrap;
typedef imtauthgql::CRemotePermissionCheckerComp RemotePermissionChecker;
typedef imtauthgql::CSessionModelObserverComp SessionModelObserver;
typedef imtauthgql::CSessionModelSubscriberControllerComp SessionModelSubscriberController;
typedef imtauthgql::CLdapAuthorizationControllerComp LdapAuthorizationController;
typedef imtauthgql::CUserSerializableCollectionControllerComp UserSerializableCollectionController;
typedef imtauthgql::CUserSettingsControllerComp UserSettingsController;
typedef imtauthgql::CProfileControllerComp ProfileController;
typedef imtauthgql::CRoleRemoteCollectionControllerComp RoleRemoteCollectionController;
typedef imtauthgql::CRemoteJwtSessionControllerComp RemoteJwtSessionController;
typedef imtauthgql::CGqlJwtSessionControllerComp GqlJwtSessionController;
typedef imtauthgql::CRoleMetaInfoDelegateComp RoleMetaInfoDelegate;
typedef imtauthgql::CUserMetaInfoDelegateComp UserMetaInfoDelegate;
typedef imtauthgql::CGroupMetaInfoDelegateComp GroupMetaInfoDelegate;
typedef imtauthgql::CRemoteUserControllerComp RemoteUserController;
typedef imtauthgql::CRemoteAuthorizationControllerComp RemoteAuthorizationController;
typedef imtauthgql::CUserActionCollectionControllerComp UserActionCollectionController;
typedef imtauthgql::CUserActionMetaInfoDelegateComp UserActionMetaInfoDelegate;
typedef icomp::TModelCompWrap<imtauthgql::CSimpleLoginComp> SimpleLogin;
typedef imtauthgql::CClientRequestRoleManagerComp ClientRequestRoleManager;
typedef imtauthgql::CClientRequestUserManagerComp ClientRequestUserManager;
typedef imtauthgql::CClientRequestGroupManagerComp ClientRequestGroupManager;
typedef imtauthgql::CClientRequestUserInfoProviderComp ClientRequestUserInfoProvider;
typedef imtauthgql::CClientRequestRoleInfoProviderComp ClientRequestRoleInfoProvider;
typedef imtauthgql::CClientRequestGroupInfoProviderComp ClientRequestGroupInfoProvider;
typedef imtauthgql::CTokenBasedPermissionsProviderComp ClientRequestTokenBasedPermissionsProvider;
typedef imtauthgql::CPersonalAccessTokenControllerComp PersonalAccessTokenController;
typedef icomp::TModelCompWrap<imtauthgql::CClientRequestPersonalAccessTokenManagerComp> ClientRequestPersonalAccessTokenManager;
typedef imtauthgql::CTenantCollectionControllerComp TenantCollectionController;
typedef imtauthgql::CTenantMetaInfoDelegateComp TenantMetaInfoDelegate;
typedef imtauthgql::CTenantCollectionDocumentServiceComp TenantCollectionDocumentService;
typedef imtauthgql::CRemoteProfileControllerComp RemoteProfileController;
typedef imtauthgql::CJwtSessionControllerProxyComp JwtSessionControllerProxy;
typedef imtauthgql::CRemoteTenantControllerComp RemoteTenantController;
typedef imtauthgql::CRemoteTenantMembershipManagerControllerComp RemoteTenantMembershipManagerController;
typedef imtauthgql::CTenantManagerControllerComp TenantManagerController;
typedef imtauthgql::CTenantMembershipManagerControllerComp TenantMembershipManagerController;
typedef imtauthgql::CTenantMembershipPublisherComp TenantMembershipPublisher;
typedef imtauthgql::CRemoteTenantCollectionDocumentServiceControllerComp RemoteTenantCollectionDocumentService;


} // namespace ImtAuthGqlPck

