INCLUDEPATH += $(IMTCOREDIR)/Include
INCLUDEPATH += $(IMTCOREDIR)/Impl
INCLUDEPATH += $(IMTCOREDIR)/$$AUXINCLUDEDIR

LIBS += -L$(IMTCOREDIR)/Lib/$$COMPILER_DIR
LIBS += -limt3d -limtgui -lImtCoreLoc

