include($(ACFSLNDIR)/Config/QMake/AcfSln.pri)
include($(IACFDIR)/Config/QMake/Iacf.pri)

INCLUDEPATH += $(IMTCOREDIR)/Include
INCLUDEPATH += $(IMTCOREDIR)/Impl
INCLUDEPATH += $(IMTCOREDIR)/$$AUXINCLUDEDIR

win32{
	LIBS += -ladvapi32 -luser32
}

IMTCOREDIRBUILD = $$(IMTCOREDIR_BUILD)
!isEmpty(IMTCOREDIRBUILD){
	INCLUDEPATH += $$(IMTCOREDIRBUILD)/$$AUXINCLUDEDIR
	LIBS += -L$$(IMTCOREDIRBUILD)/Lib/$$COMPILER_DIR
}
else{
	LIBS += -L$$PWD/../../Lib/$$COMPILER_DIR
}

