
GENERATED_WEB_RESOURCE_OUTPUT = $${buildwebdir}/Resources/qrc_$${TARGET}Web.cpp
win32:GENERATED_WEB_RESOURCE_OUTPUT ~= s,/,\\,g

webQrc$${TARGET}.target = $${GENERATED_WEB_RESOURCE_OUTPUT}
webQrc$${TARGET}.commands = echo $${GENERATED_WEB_RESOURCE_OUTPUT}
QMAKE_EXTRA_TARGETS += webQrc$${TARGET}
GENERATED_SOURCES += $${GENERATED_WEB_RESOURCE_OUTPUT}
