const QtObject = require("../../QtQml/QtObject")
const Real = require("../../QtQml/Real")
const Var = require("../../QtQml/Var")
const String = require("../../QtQml/String")
const Signal = require("../../QtQml/Signal")

class Popup extends QtObject {
    static meta = Object.assign({}, QtObject.meta, {
        activeFocus: { type: Var, value: false },
        anchors: { type: Var },
        availableHeight: { type: Real, value: 0 },
        availableWidth: { type: Real, value: 0 },
        background: { type: Var },
        bottomInset: { type: Real, value: 0 },
        bottomMargin: { type: Real, value: -1 },
        bottomPadding: { type: Real, value: 0 },
        clip: { type: Var, value: false },
        closePolicy: { type: Var, value: 5 },
        contentChildren: { type: Var, value: [] },
        contentData: { type: Var, value: [] },
        contentHeight: { type: Real, value: 0 },
        contentItem: { type: Var },
        contentWidth: { type: Real, value: 0 },
        dim: { type: Var },
        enabled: { type: Var, value: true },
        enter: { type: Var },
        exit: { type: Var },
        focus: { type: Var, value: false },
        font: { type: Var },
        height: { type: Real, value: 0 },
        horizontalPadding: { type: Real, value: 0 },
        implicitBackgroundHeight: { type: Real, value: 0 },
        implicitBackgroundWidth: { type: Real, value: 0 },
        implicitContentHeight: { type: Real, value: 0 },
        implicitContentWidth: { type: Real, value: 0 },
        implicitHeight: { type: Real, value: 0 },
        implicitWidth: { type: Real, value: 0 },
        leftInset: { type: Real, value: 0 },
        leftMargin: { type: Real, value: -1 },
        leftPadding: { type: Real, value: 0 },
        locale: { type: Var },
        margins: { type: Real, value: -1 },
        mirrored: { type: Var, value: false },
        modal: { type: Var, value: false },
        opacity: { type: Real, value: 1 },
        opened: { type: Var, value: false },
        padding: { type: Real, value: 0 },
        palette: { type: Var },
        parent: { type: Var },
        popupType: { type: Var, value: 0 },
        rightInset: { type: Real, value: 0 },
        rightMargin: { type: Real, value: -1 },
        rightPadding: { type: Real, value: 0 },
        scale: { type: Real, value: 1 },
        spacing: { type: Real, value: 0 },
        topInset: { type: Real, value: 0 },
        topMargin: { type: Real, value: -1 },
        topPadding: { type: Real, value: 0 },
        transformOrigin: { type: Var, value: 4 },
        verticalPadding: { type: Real, value: 0 },
        visible: { type: Var, value: false },
        wheelEnabled: { type: Var, value: false },
        width: { type: Real, value: 0 },
        x: { type: Real, value: 0 },
        y: { type: Real, value: 0 },
        z: { type: Real, value: 0 },
        
        activeFocusChanged: { type: Signal, args: [] },
        anchorsChanged: { type: Signal, args: [] },
        availableHeightChanged: { type: Signal, args: [] },
        availableWidthChanged: { type: Signal, args: [] },
        backgroundChanged: { type: Signal, args: [] },
        bottomInsetChanged: { type: Signal, args: [] },
        bottomMarginChanged: { type: Signal, args: [] },
        bottomPaddingChanged: { type: Signal, args: [] },
        clipChanged: { type: Signal, args: [] },
        closePolicyChanged: { type: Signal, args: [] },
        contentChildrenChanged: { type: Signal, args: [] },
        contentDataChanged: { type: Signal, args: [] },
        contentHeightChanged: { type: Signal, args: [] },
        contentItemChanged: { type: Signal, args: [] },
        contentWidthChanged: { type: Signal, args: [] },
        dimChanged: { type: Signal, args: [] },
        enabledChanged: { type: Signal, args: [] },
        enterChanged: { type: Signal, args: [] },
        exitChanged: { type: Signal, args: [] },
        focusChanged: { type: Signal, args: [] },
        fontChanged: { type: Signal, args: [] },
        heightChanged: { type: Signal, args: [] },
        horizontalPaddingChanged: { type: Signal, args: [] },
        implicitBackgroundHeightChanged: { type: Signal, args: [] },
        implicitBackgroundWidthChanged: { type: Signal, args: [] },
        implicitContentHeightChanged: { type: Signal, args: [] },
        implicitContentWidthChanged: { type: Signal, args: [] },
        implicitHeightChanged: { type: Signal, args: [] },
        implicitWidthChanged: { type: Signal, args: [] },
        leftInsetChanged: { type: Signal, args: [] },
        leftMarginChanged: { type: Signal, args: [] },
        leftPaddingChanged: { type: Signal, args: [] },
        localeChanged: { type: Signal, args: [] },
        marginsChanged: { type: Signal, args: [] },
        mirroredChanged: { type: Signal, args: [] },
        modalChanged: { type: Signal, args: [] },
        opacityChanged: { type: Signal, args: [] },
        openedChanged: { type: Signal, args: [] },
        paddingChanged: { type: Signal, args: [] },
        paletteChanged: { type: Signal, args: [] },
        parentChanged: { type: Signal, args: [] },
        popupTypeChanged: { type: Signal, args: [] },
        rightInsetChanged: { type: Signal, args: [] },
        rightMarginChanged: { type: Signal, args: [] },
        rightPaddingChanged: { type: Signal, args: [] },
        scaleChanged: { type: Signal, args: [] },
        spacingChanged: { type: Signal, args: [] },
        topInsetChanged: { type: Signal, args: [] },
        topMarginChanged: { type: Signal, args: [] },
        topPaddingChanged: { type: Signal, args: [] },
        transformOriginChanged: { type: Signal, args: [] },
        verticalPaddingChanged: { type: Signal, args: [] },
        visibleChanged: { type: Signal, args: [] },
        wheelEnabledChanged: { type: Signal, args: [] },
        widthChanged: { type: Signal, args: [] },
        xChanged: { type: Signal, args: [] },
        yChanged: { type: Signal, args: [] },
        zChanged: { type: Signal, args: [] },
        
        closed: { type: Signal, args: [] },
        opened: { type: Signal, args: [] },
        aboutToHide: { type: Signal, args: [] },
        aboutToShow: { type: Signal, args: [] }
    })

    static create(parent = null, properties = {}){
        let obj = super.create(parent, properties)

        return obj
    }

}



module.exports = Popup