-- Legacy TenantConnectionRequests table kept for migration reference.
-- New schema uses tables in CreateTenantRelationshipsTable.sql:
--   TenantConnectionCodes, TenantConnectionRequests, TenantConnections,
--   TenantRelationships, TenantRelationshipProposals.
