/********************************************************************************
	autogenerated code from GQL schema
	\code GQL
	schema {
		name: SdlCache
		namespace: imtsdl
	}

	type CacheEntry {
		TypeId: String!
		QmlEntryName: String!
		TargetHeaderPath: String!
		Namespace: String!
		TargetSourceRelativePath: String
		Version: String
	}

	type Cache {
		IncludePaths: [String!]!
		Types: [CacheEntry!]!
	}
	\endcode GQL
********************************************************************************/


/// \file CCacheEntry.h

#pragma once


// Qt includes
#include <QtCore/QJsonObject>
#include <QtCore/QJsonArray>
#include <QtCore/QJsonValue>
#include <QtCore/QString>
#include <QtCore/QVariant>
#include <QtCore/QVariantMap>
#include <QtCore/QSet>
#include <QtCore/QList>

// ACF includes
#include <istd/TPointerVector.h>
#include <iser/ISerializable.h>
#include <imod/TModelWrap.h>
#include <imod/CModelUpdateBridge.h>

// ImtCore includes
#include <imtbase/CTreeItemModel.h>
#include <imtgql/CGqlObject.h>


namespace imtsdl
{

class CCacheEntry: public istd::IChangeable
{
public:
	struct CacheEntryFields
	{
		static const inline QString TypeId = "TypeId";
		static const inline QString QmlEntryName = "QmlEntryName";
		static const inline QString TargetHeaderPath = "TargetHeaderPath";
		static const inline QString Namespace = "Namespace";
		static const inline QString TargetSourceRelativePath = "TargetSourceRelativePath";
		static const inline QString Version = "Version";
	};

	[[nodiscard]] QString GetTypeId() const;
	void SetTypeId(const QString& typeId);

	[[nodiscard]] QString GetQmlEntryName() const;
	void SetQmlEntryName(const QString& qmlEntryName);

	[[nodiscard]] QString GetTargetHeaderPath() const;
	void SetTargetHeaderPath(const QString& targetHeaderPath);

	[[nodiscard]] QString GetNamespace() const;
	void SetNamespace(const QString& aNamespace);

	[[nodiscard]] QString GetTargetSourceRelativePath() const;
	void SetTargetSourceRelativePath(const QString& targetSourceRelativePath);

	[[nodiscard]] QString GetVersion() const;
	void SetVersion(const QString& version);

	[[nodiscard]] bool WriteToJsonObject(QJsonObject& jsonObject) const;
	[[nodiscard]] static bool ReadFromJsonObject(CCacheEntry& object, const QJsonObject& jsonObject);

	bool operator==(const CCacheEntry& other) const;
	bool operator!=(const CCacheEntry& other) const { return !(operator==(other)); }

	// reimplemented (istd::IChangeable)
	virtual int GetSupportedOperations() const override;
	virtual bool CopyFrom(const IChangeable& object, CompatibilityMode mode = istd::IChangeable::CM_WITHOUT_REFS) override;
	virtual bool IsEqual(const IChangeable& object) const override;
	virtual bool ResetData(CompatibilityMode mode = istd::IChangeable::CM_WITHOUT_REFS) override;

private:
	QString m_typeId;
	QString m_qmlEntryName;
	QString m_targetHeaderPath;
	QString m_namespace;
	QString m_targetSourceRelativePath;
	QString m_version;

};


/// \file CCache.h


class CCache: public istd::IChangeable
{
public:
	struct CacheFields
	{
		static const inline QString IncludePaths = "IncludePaths";
		static const inline QString Types = "Types";
	};

	CCache();
	CCache(const CCache& other);

	[[nodiscard]] QList<QString> GetIncludePaths() const;
	void SetIncludePaths(const QList<QString>& includePaths);
	void AddIncludePathsElement(const QString& element);

	[[nodiscard]] istd::TPointerVector<CCacheEntry> GetTypes() const;
	void AddTypesElement(const CCacheEntry& element);

	[[nodiscard]] bool WriteToJsonObject(QJsonObject& jsonObject) const;
	[[nodiscard]] static bool ReadFromJsonObject(CCache& object, const QJsonObject& jsonObject);

	bool operator==(const CCache& other) const;
	bool operator!=(const CCache& other) const { return !(operator==(other)); }

	// reimplemented (istd::IChangeable)
	virtual int GetSupportedOperations() const override;
	virtual bool CopyFrom(const IChangeable& object, CompatibilityMode mode = istd::IChangeable::CM_WITHOUT_REFS) override;
	virtual bool IsEqual(const IChangeable& object) const override;
	virtual bool ResetData(CompatibilityMode mode = istd::IChangeable::CM_WITHOUT_REFS) override;

private:
	QList<QString> m_includePaths;
	istd::TPointerVector<CCacheEntry> m_types;

	imod::CModelUpdateBridge m_updateBridge;
};


} // namespace imtsdl


Q_DECLARE_METATYPE(imtsdl::CCacheEntry);

Q_DECLARE_METATYPE(imtsdl::CCache);

