/** autogenerated code from GQL schema
	\code GQL
	schema {
		name: SdlCache
		namespace: imtsdl
	}

	type CacheEntry {
		TypeId: String!
		QmlEntryName: String!
		TargetHeaderPath: String!
		Namespace: String!
		TargetSourceRelativePath: String
		Version: String
	}

	type Cache {
		IncludePaths: [String!]!
		Types: [CacheEntry!]!
	}
	\endcode GQL
 */


/// \file CCacheEntry.h

#pragma once


//Qt includes
#include <QtCore/QJsonObject>
#include <QtCore/QJsonArray>
#include <QtCore/QJsonValue>
#include <QtCore/QString>
#include <QtCore/QVariant>
#include <QtCore/QVariantMap>
#include <QtCore/QSet>
#include <QtCore/QList>

//ImtCore includes
#include <imtbase/CTreeItemModel.h>
#include <imtgql/CGqlObject.h>


namespace imtsdl
{

class CCacheEntry
{
public:
	struct CacheEntryFields
	{
		static const inline QString TypeId = "TypeId";
		static const inline QString QmlEntryName = "QmlEntryName";
		static const inline QString TargetHeaderPath = "TargetHeaderPath";
		static const inline QString Namespace = "Namespace";
		static const inline QString TargetSourceRelativePath = "TargetSourceRelativePath";
		static const inline QString Version = "Version";
	};

	[[nodiscard]] QString GetTypeId() const;
	void SetTypeId(const QString& typeId);
	void ResetTypeId();
	[[nodiscard]] bool HasTypeId() const;

	[[nodiscard]] QString GetQmlEntryName() const;
	void SetQmlEntryName(const QString& qmlEntryName);
	void ResetQmlEntryName();
	[[nodiscard]] bool HasQmlEntryName() const;

	[[nodiscard]] QString GetTargetHeaderPath() const;
	void SetTargetHeaderPath(const QString& targetHeaderPath);
	void ResetTargetHeaderPath();
	[[nodiscard]] bool HasTargetHeaderPath() const;

	[[nodiscard]] QString GetNamespace() const;
	void SetNamespace(const QString& aNamespace);
	void ResetNamespace();
	[[nodiscard]] bool HasNamespace() const;

	[[nodiscard]] QString GetTargetSourceRelativePath() const;
	void SetTargetSourceRelativePath(const QString& targetSourceRelativePath);
	void ResetTargetSourceRelativePath();
	[[nodiscard]] bool HasTargetSourceRelativePath() const;

	[[nodiscard]] QString GetVersion() const;
	void SetVersion(const QString& version);
	void ResetVersion();
	[[nodiscard]] bool HasVersion() const;

	[[nodiscard]] bool WriteToJsonObject(QJsonObject& jsonObject) const;
	[[nodiscard]] static bool ReadFromJsonObject(CCacheEntry& object, const QJsonObject& jsonObject);

	bool operator==(const CCacheEntry& other) const;
	bool operator!=(const CCacheEntry& other) const { return !(operator==(other)); }

private:
	QString m_typeId;
	QString m_qmlEntryName;
	QString m_targetHeaderPath;
	QString m_namespace;
	QString m_targetSourceRelativePath;
	QString m_version;
	QSet<QByteArray/*FieldId*/> _m_settedFields;
};


/// \file CCache.h

class CCache
{
public:
	struct CacheFields
	{
		static const inline QString IncludePaths = "IncludePaths";
		static const inline QString Types = "Types";
	};

	[[nodiscard]] QList<QString> GetIncludePaths() const;
	void SetIncludePaths(const QList<QString>& includePaths);
	void AddIncludePathsElement(const QString& element);
	void ResetIncludePaths();
	[[nodiscard]] bool HasIncludePaths() const;

	[[nodiscard]] QList<CCacheEntry> GetTypes() const;
	void SetTypes(const QList<CCacheEntry>& types);
	void AddTypesElement(const CCacheEntry& element);
	void ResetTypes();
	[[nodiscard]] bool HasTypes() const;

	[[nodiscard]] bool WriteToJsonObject(QJsonObject& jsonObject) const;
	[[nodiscard]] static bool ReadFromJsonObject(CCache& object, const QJsonObject& jsonObject);

	bool operator==(const CCache& other) const;
	bool operator!=(const CCache& other) const { return !(operator==(other)); }

private:
	QList<QString> m_includePaths;
	QList<CCacheEntry> m_types;
	QSet<QByteArray/*FieldId*/> _m_settedFields;
};


} // namespace imtsdl


Q_DECLARE_METATYPE(imtsdl::CCacheEntry);

Q_DECLARE_METATYPE(imtsdl::CCache);

