
function(GenerateDdlCodeExt MODULE_CPP_NAME MODULE_QML_NAME DDL_CONST_VAR_TEMPLATE_INPUT_DIR DDL_CPP_OUTPUT_DIR DDL_QML_OUTPUT_DIR)


#----------------------------------------------------------- The DESIGN TOKEN CREATOR config
# Setting the executable file name for specific OS
get_target_name(TARGETNAME)
#message ("number of arguments sent to function: ${ARGC}")
#message ("all function arguments:               ${ARGV}")
message("GenerateDdlCodeExt ${PROJECT_NAME} TARGETNAME ${TARGETNAME}")
set(COMPILER_DIR ${CMAKE_BUILD_TYPE}_${TARGETNAME})
string(FIND "$ENV{ARXCHOST}" "VC" POSITION_OF_VC)
if (WIN32 OR (${POSITION_OF_VC} GREATER_EQUAL 0))
	set(DDL_CODE_CREATOR_EXE "DdlCodeCreator.exe")
else()
	set(DDL_CODE_CREATOR_EXE "DdlCodeCreator")
endif()

#  Setting the executable absolutely file path for specific OS
if(ANDROID)
		set(DDL_CODE_CREATOR_EXE_BIN "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Bin/${CMAKE_BUILD_TYPE}_$ENV{ARXCHOST}/${DDL_CODE_CREATOR_EXE}")
else()
		set(DDL_CODE_CREATOR_EXE_BIN "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Bin/${COMPILER_DIR}/${DDL_CODE_CREATOR_EXE}")
endif()

message("DDL_CODE_CREATOR_EXE_BIN ${DDL_CODE_CREATOR_EXE_BIN}")
message("DDL_CONST_VAR_TEMPLATE_INPUT_DIR ${DDL_CONST_VAR_TEMPLATE_INPUT_DIR}")
message("DDL_CPP_OUTPUT_DIR ${DDL_CPP_OUTPUT_DIR}")
message("DDL_QML_OUTPUT_DIR ${DDL_QML_OUTPUT_DIR}")

string(TOLOWER ${PROJECT_NAME} LOWER_PROJECT_NAME)

set(CONST_VAR_CREATOR_COMMAND_PARAMS
	-TD
		${DDL_CONST_VAR_TEMPLATE_INPUT_DIR}
	-CD
		${DDL_CPP_OUTPUT_DIR}
	-QD
		${DDL_QML_OUTPUT_DIR}
	-MODC
		${MODULE_CPP_NAME}
	-MODQ
		${MODULE_QML_NAME}
	)

#set(QRC_QRC_FILES)

# additional deps for maintain integrity of build
file(GLOB DDL_CONST_VAR_TEMPLATE_INPUT_FILES "${DDL_CONST_VAR_TEMPLATE_INPUT_DIR}/*")
set(CONST_VAR_TEMPLATE_INPUT_DIR_LENGTH 0)
if(DDL_CONST_VAR_TEMPLATE_INPUT_DIR)
	string(LENGTH ${DDL_CONST_VAR_TEMPLATE_INPUT_DIR} CONST_VAR_TEMPLATE_INPUT_DIR_LENGTH)
endif()

if(CONST_VAR_TEMPLATE_INPUT_DIR_LENGTH GREATER 2)
	list(APPEND DDL_TEMPLATE_FILES ${DDL_CONST_VAR_TEMPLATE_INPUT_FILES})
endif()

set(H_OUTPUT_FILE ${DDL_CPP_OUTPUT_DIR}/Globals.h)
set(CPP_OUTPUT_FILE ${DDL_CPP_OUTPUT_DIR}/Globals.cpp)

target_sources(${PROJECT_NAME} PRIVATE ${H_OUTPUT_FILE} ${CPP_OUTPUT_FILE})

add_custom_command(
	OUTPUT
		${CPP_OUTPUT_FILE}
		${H_OUTPUT_FILE}
	COMMAND
		${DDL_CODE_CREATOR_EXE_BIN}
	ARGS
		${CONST_VAR_CREATOR_COMMAND_PARAMS}
	DEPENDS
		${DDL_CODE_CREATOR_EXE_BIN} ${DDL_CONST_VAR_TEMPLATE_INPUT_FILES}
	COMMENT
		"[ConstVarCreator::${LOWER_PROJECT_NAME}] Creating CPP ${CPP_OUTPUT_FILE}, Creating H ${H_OUTPUT_FILE}"
	VERBATIM
	)

add_custom_target(
		ConstVarCreator${PROJECT_NAME}${DESIGN_TOKEN_CREATOR_CUSTOM_TARGET} ALL
        DEPENDS ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignToken.stamp
        )

endfunction()
