#----------------------------------------------------------- The DESIGN TOKEN CREATOR config
# Setting the executable file name for specific OS
set(COMPILER_DIR ${CMAKE_BUILD_TYPE}_${TARGETNAME})
string(FIND "$ENV{ARXCHOST}" "VC" POSITION_OF_VC)
if (WIN32 OR (${POSITION_OF_VC} EQUAL 4))
	set(DESIGN_TOKEN_CREATOR_EXE "DesignTokenCreator.exe")
else()
	set(DESIGN_TOKEN_CREATOR_EXE "DesignTokenCreator")
endif()


file(GLOB DESIGN_TOKEN_CREATOR_INPUT_THEME_FILES "${IMTCOREDIR}/Include/imtstyle/*.theme")

#  Setting the executable absolutely file path for specific OS
if(ANDROID)
        set(DESIGN_TOKEN_CREATOR_EXE_BIN "${CMAKE_CURRENT_SOURCE_DIR}/../../../Bin/${CMAKE_BUILD_TYPE}_$ENV{ARXCHOST}/${DESIGN_TOKEN_CREATOR_EXE}")
else()
	set(DESIGN_TOKEN_CREATOR_EXE_BIN "${CMAKE_CURRENT_SOURCE_DIR}/../../../Bin/${COMPILER_DIR}/${DESIGN_TOKEN_CREATOR_EXE}")
endif()


string(TOLOWER ${PROJECT_NAME} LOWER_PROJECT_NAME)

set(DESIGN_TOKEN_CREATOR_COMMAND_PARAMS
	-I
		${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_DIR}
	-S
		${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_DIR}
	-OD
		${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}
	-P
		${LOWER_PROJECT_NAME}
	)

set(QRC_QRC_FILES)

# additional deps for maintain integrity of build
file(GLOB DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_FILES "${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_DIR}/*")
file(GLOB DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_FILES "${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_DIR}/*")
set(IMAGES_INPUT_DIR_LENGTH 0)
set(STYIES_INPUT_DIR_LENGTH 0)
if(DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_DIR)
	string(LENGTH ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_DIR} IMAGES_INPUT_DIR_LENGTH)
endif()
if(DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_DIR)
	string(LENGTH ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_DIR} STYIES_INPUT_DIR_LENGTH)
endif()
if(IMAGES_INPUT_DIR_LENGTH GREATER 2)
	list(APPEND DESIGN_TOKEN_SOURCE_FILES ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_IMAGES_INPUT_FILES})
endif()
if(STYIES_INPUT_DIR_LENGTH GREATER 2)
	list(APPEND DESIGN_TOKEN_SOURCE_FILES ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_STYIES_INPUT_FILES})
endif()
list(APPEND DESIGN_TOKEN_SOURCE_FILES ${DESIGN_TOKEN_CREATOR_INPUT_THEME_FILES})

foreach(_file ${DESIGN_TOKEN_CREATOR_INPUT_THEME_FILES})
	string(REPLACE "/" ";" CURRENT_FILE_PARTS ${_file})
	list(GET CURRENT_FILE_PARTS -1 CURRENT_FILE_NAME_WITH_EXT)
	string(REPLACE "." ";" CURRENT_FILE_NAME_WITH_NO_EXT ${CURRENT_FILE_NAME_WITH_EXT})
	list(GET CURRENT_FILE_NAME_WITH_NO_EXT 0 CURRENT_FILE_NAME)

	set(QRC_QRC_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${LOWER_PROJECT_NAME}${CURRENT_FILE_NAME}.qrc)
	set(QRC_CPP_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/qrc_${LOWER_PROJECT_NAME}${CURRENT_FILE_NAME}.cpp)

	target_sources(${PROJECT_NAME} PRIVATE ${QRC_CPP_CURRENT_FILE})

	add_custom_command(
		OUTPUT
			${QRC_QRC_CURRENT_FILE}
		COMMAND
			${DESIGN_TOKEN_CREATOR_EXE_BIN}
		ARGS
			${DESIGN_TOKEN_CREATOR_COMMAND_PARAMS} -F ${_file}
		DEPENDS
			${DESIGN_TOKEN_CREATOR_EXE_BIN} ${DESIGN_TOKEN_SOURCE_FILES}
		COMMENT
			"[DesignToken::${LOWER_PROJECT_NAME}] Creating QRC ${QRC_QRC_CURRENT_FILE}"
		VERBATIM
		)

	add_custom_command(
		OUTPUT ${QRC_CPP_CURRENT_FILE}
		COMMAND
		Qt${QT_VERSION_MAJOR}::rcc
		ARGS
			-name ${LOWER_PROJECT_NAME}${CURRENT_FILE_NAME} ${QRC_QRC_CURRENT_FILE} -o ${QRC_CPP_CURRENT_FILE}
		DEPENDS
			${QRC_QRC_CURRENT_FILE} ${DESIGN_TOKEN_SOURCE_FILES}
		COMMENT
			"[DesignToken::${LOWER_PROJECT_NAME}] CREATING RES ${QRC_CPP_CURRENT_FILE}"
	)

	list(APPEND QRC_QRC_FILES ${QRC_CPP_CURRENT_FILE})

endforeach()

set(QRC_CPP_WEB_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/qrc_Web${LOWER_PROJECT_NAME}.cpp)
set(QRC_QRC_WEB_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/Web${LOWER_PROJECT_NAME}.qrc)
target_sources(${PROJECT_NAME} PRIVATE ${QRC_CPP_WEB_CURRENT_FILE})

add_custom_command(
	OUTPUT
	    ${QRC_QRC_WEB_CURRENT_FILE}
	COMMAND
	    ${DESIGN_TOKEN_CREATOR_EXE_BIN}
	ARGS
	     ${DESIGN_TOKEN_CREATOR_COMMAND_PARAMS} -W -F ${_file} --ignore-errors
	DEPENDS
	    ${QRC_QRC_FILES}
        COMMENT
		"[DesignToken::${LOWER_PROJECT_NAME}] Creating QRC ${QRC_QRC_WEB_CURRENT_FILE}"
	VERBATIM
	)

add_custom_command(
	OUTPUT ${QRC_CPP_WEB_CURRENT_FILE}
	COMMAND
	Qt${QT_VERSION_MAJOR}::rcc
	ARGS
	    -name Web${PROJECT_NAME} ${QRC_QRC_WEB_CURRENT_FILE} -o ${QRC_CPP_WEB_CURRENT_FILE}
	DEPENDS
	    ${QRC_QRC_WEB_CURRENT_FILE}
		COMMENT
		"[DesignToken::${LOWER_PROJECT_NAME}] CREATING RES ${QRC_CPP_WEB_CURRENT_FILE}"
)


list(APPEND QRC_QRC_FILES ${QRC_CPP_WEB_CURRENT_FILE})

add_custom_command(
	OUTPUT
                ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignToken.stamp
	COMMAND
                ${CMAKE_COMMAND} -E touch ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignToken.stamp
	COMMENT
		"[DesignToken::${PROJECT_NAME}] Creating done"
	DEPENDS
		${QRC_QRC_FILES} ${DESIGN_TOKEN_SOURCE_FILES}
	VERBATIM
	)

add_custom_target(
        DesignToken${PROJECT_NAME} ALL
        DEPENDS ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignToken.stamp
	)
