include_directories(${IMTCOREDIR}/3rdParty/libduckdb/include)

if(APPLE)
	if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
		target_link_libraries(${PROJECT_NAME} PUBLIC ${IMTCOREDIR}/3rdParty/libduckdb/lib/ClangOSX_arm64/libduckdb.dylib)
	else()
		target_link_libraries(${PROJECT_NAME} PUBLIC ${IMTCOREDIR}/3rdParty/libduckdb/lib/ClangOSX_x64/libduckdb.dylib)
	endif()
else()
	message(WARNING "DuckDb.cmake: no prebuilt DuckDB binaries available for this platform in 3rdParty/libduckdb/lib")
endif()
