function(ImtCoreGenerateSdl
	SDL_GENERATOR_COMMAND_PARAM_INPUT_FILE_PATH,
	SDL_GENERATOR_COMMAND_PARAM_OUTPUT_DIR,
	SDL_GENERATOR_COMMAND_PARAM_NAMESPACE)
#{
	# The SDL code generator config
	# Setting the executable file name for specific OS
	get_target_name(TARGETNAME)

	message(STATUS "SDL generation for ${PROJECT_NAME} TARGETNAME ${TARGETNAME}")

	set(COMPILER_DIR ${CMAKE_BUILD_TYPE}_${TARGETNAME})
	string(FIND "$ENV{ARXCHOST}" "VC" POSITION_OF_VC)
	if (WIN32 OR (${POSITION_OF_VC} GREATER_EQUAL 0))
		set(SDL_GENERATOR_EXE_NAME "SdlCodeGenerator.exe")
	else()
		set(SDL_GENERATOR_EXE_NAME "SdlCodeGenerator")
	endif()

	#  Setting the executable absolutely file path for specific OS
	if(ANDROID)
			set(SDL_GENERATOR_EXE_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Bin/${CMAKE_BUILD_TYPE}_$ENV{ARXCHOST}/${SDL_GENERATOR_EXE_NAME}")
	else()
			set(SDL_GENERATOR_EXE_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Bin/${COMPILER_DIR}/${SDL_GENERATOR_EXE_NAME}")
	endif()

	# Generate a dependencies list to be generated
	set (SDL_DEPS_GENERATION_COMMAND "${SDL_GENERATOR_EXE_PATH} -DS ${SDL_GENERATOR_COMMAND_PARAM_INPUT_FILE_PATH} -O ${SDL_GENERATOR_COMMAND_PARAM_OUTPUT_DIR}")
	execute_process(
		COMMAND
			${SDL_DEPS_GENERATION_COMMAND}
		OUTPUT_FILE
			${SDL_DEPS_FILE_PATH}
		ERROR_FILE
			${SDL_ERRORS_FILE_PATH}
		RESULT_VARIABLE
			SDL_DEPS_GENERATION_RESULT_CODE
	)

	if(NOT SDL_DEPS_GENERATION_RESULT_CODE EQUAL 0)
		message(WARNING "SDL Cannot to create dependens")

		file(STRINGS ${SDL_DEPS_FILE_PATH} ERRORS1_SDL_DEPS_LIST)
		message("${ERRORS1_SDL_DEPS_LIST}")

		file(STRINGS ${SDL_ERRORS_FILE_PATH} ERRORS2_SDL_DEPS_LIST)
		message("${ERRORS2_SDL_DEPS_LIST}")

		execute_process(COMMAND ${SDL_DEPS_GENERATION_COMMAND})
		message("${SDL_DEPS_GENERATION_COMMAND}")
		message(FATAL_ERROR "SDL finished unexpected. Error code: [${SDL_DEPS_GENERATION_RESULT_CODE}]")
	endif()

	file(STRINGS ${SDL_DEPS_FILE_PATH} SDL_GENERATED_DEPS)

	add_custom_command(
		OUTPUT
			${SDL_GENERATED_DEPS}
		COMMAND
			${SDL_GENERATOR_EXE_PATH}
		ARGS
			-GS ${SDL_GENERATOR_COMMAND_PARAM_INPUT_FILE_PATH} -O ${SDL_GENERATOR_COMMAND_PARAM_OUTPUT_DIR} -N ${SDL_GENERATOR_COMMAND_PARAM_NAMESPACE}
		DEPENDS
			${SDL_GENERATOR_EXE_PATH} ${SDL_GENERATOR_COMMAND_PARAM_INPUT_FILE_PATH}
		COMMENT
			"[SDL::${PROJECT_NAME}] Creating classes"
		VERBATIM
	)

	target_sources(${PROJECT_NAME} PRIVATE ${SDL_GENERATED_DEPS})

endfunction()
