function(imt_core_get_root_dir identifier_to_use)
    set(${identifier_to_use} "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." PARENT_SCOPE)
endfunction()

function(GenerateDesignTokenWeb DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR DESIGN_TOKEN_ADDITIONAL_DEPS)


#----------------------------------------------------------- The DESIGN TOKEN CREATOR config
# Setting the executable file name for specific OS
get_target_name(TARGETNAME)
message("GenerateDesignTokenWeb ${PROJECT_NAME} TARGETNAME ${TARGETNAME}")

set(COMPILER_DIR ${CMAKE_BUILD_TYPE}_${TARGETNAME})
if (WIN32)
	set(DESIGN_TOKEN_CREATOR_EXE "DesignTokenCreator.exe")
else()
	set(DESIGN_TOKEN_CREATOR_EXE "DesignTokenCreator")
endif()

#  Setting the executable absolutely file path for specific OS
set(DESIGN_TOKEN_CREATOR_EXE_BIN "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Bin/${COMPILER_DIR}/${DESIGN_TOKEN_CREATOR_EXE}")

string(TOLOWER ${PROJECT_NAME} LOWER_PROJECT_NAME)

set(DESIGN_TOKEN_CREATOR_COMMAND_PARAMS
	-W
	-OD
		${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}
	-P
		${LOWER_PROJECT_NAME}
	)


set(QRC_CPP_WEB_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/qrc_Web${LOWER_PROJECT_NAME}.cpp)
set(QRC_QRC_WEB_CURRENT_FILE ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/Web${LOWER_PROJECT_NAME}.qrc)

target_sources(${PROJECT_NAME} PRIVATE ${QRC_CPP_WEB_CURRENT_FILE})

string(REPLACE ";" " " ADDITIONAL_DEPS ${DESIGN_TOKEN_ADDITIONAL_DEPS})

add_custom_command(
	OUTPUT
		${QRC_QRC_WEB_CURRENT_FILE}
	COMMAND
		${DESIGN_TOKEN_CREATOR_EXE_BIN}
	ARGS
		 ${DESIGN_TOKEN_CREATOR_COMMAND_PARAMS}
	DEPENDS
		${DESIGN_TOKEN_ADDITIONAL_DEPS}
	COMMENT
		"[DesignTokenWeb::${LOWER_PROJECT_NAME}] Creating QRC ${QRC_QRC_WEB_CURRENT_FILE}"
	VERBATIM
	)

add_custom_command(
	OUTPUT ${QRC_CPP_WEB_CURRENT_FILE}
	COMMAND
	Qt${QT_VERSION_MAJOR}::rcc
	ARGS
		-name Web${PROJECT_NAME} ${QRC_QRC_WEB_CURRENT_FILE} -o ${QRC_CPP_WEB_CURRENT_FILE}
	DEPENDS
		${QRC_QRC_WEB_CURRENT_FILE}
		COMMENT
		"[DesignTokenWeb::${LOWER_PROJECT_NAME}] CREATING RES ${QRC_CPP_WEB_CURRENT_FILE}"
)

add_custom_command(
	OUTPUT
				${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignTokenWeb.stamp
	COMMAND
				${CMAKE_COMMAND} -E touch ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignToken.stamp
	COMMENT
		"[DesignTokenWeb::${PROJECT_NAME}] Creating done"
	DEPENDS
		${QRC_CPP_WEB_CURRENT_FILE} ${DESIGN_TOKEN_SOURCE_FILES}
	VERBATIM
	)

add_custom_target(
		DesignTokenWeb${PROJECT_NAME} ALL
		DEPENDS ${DESIGN_TOKEN_CREATOR_COMMAND_PARAM_OUTPUT_DIR}/${PROJECT_NAME}DesignTokenWeb.stamp
		)


endfunction()
