cmake_minimum_required(VERSION 3.1.0)

set(QT_DEFAULT_MAJOR_VERSION 5)

if(NOT DEFINED IACFDIR)
	set(IACFDIR "$ENV{IACFDIR}")
endif()
if(NOT DEFINED IMTROOTDIR)
	set(IMTROOTDIR "$ENV{IMTROOTDIR}")
endif()
if(NOT DEFINED IMTCOREDIR)
	set(IMTCOREDIR "$ENV{IMTCOREDIR}")
endif()
if(NOT DEFINED ACULADIR)
	set(ACULADIR "$ENV{ACULADIR}")
endif()
if(NOT DEFINED LISADIR)
	set(LISADIR "$ENV{LISADIR}")
endif()
if(NOT DEFINED OPENSSLDIR)
	set(OPENSSLDIR "${IMTCOREDIR}/3rdParty/openssl/1.1")
endif()
if(NOT DEFINED QUAZIP)
	set(QUAZIP "${IMTCOREDIR}/3rdParty/quazip")
endif()
if(NOT DEFINED PYTHON38DIR)
	set(PYTHON38DIR "${IMTCOREDIR}/3rdParty/Python/3.8")
endif()
if(NOT DEFINED ACFCONFIGDIR)
	set(ACFCONFIGDIR "$ENV{ACFCONFIGDIR}")
endif()
if(NOT DEFINED ZLIBDIR)
	set(ZLIBDIR "${IACFDIR}/../3rdParty/zlib")
endif()
if(NOT DEFINED NICPDIR)
	set(NICPDIR "${IMTROOTDIR}/3rdParty/nicp")
endif()


include(${IACFDIR}/Config/CMake/IAcfEnv.cmake)

include_directories("${IMTCOREDIR}/AuxInclude/Qt${QT_DEFAULT_MAJOR_VERSION}_${TARGETNAME}")
include_directories("${IMTCOREDIR}/Include")
include_directories("${IMTCOREDIR}/Impl")

link_directories("${IMTCOREDIR}/Lib/${CMAKE_BUILD_TYPE}${TARGETNAME}")
