include_directories(${IMTCOREDIR}/3rdParty/libmdbx/include)

if(WIN32)
		target_link_libraries(${PROJECT_NAME} ${IMTCOREDIR}/3rdParty/libmdbx/lib/${CMAKE_BUILD_TYPE}_${TARGETNAME}/mdbx.lib)
elseif(APPLE)
		if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
			target_link_libraries(${PROJECT_NAME} ${IMTCOREDIR}/3rdParty/libmdbx/lib/ClangOSX_arm64/libmdbx.a)
		else()
			target_link_libraries(${PROJECT_NAME} ${IMTCOREDIR}/3rdParty/libmdbx/lib/ClangOSX_x64/libmdbx.a)
		endif()
elseif(UNIX)
		target_link_libraries(${PROJECT_NAME} ${IMTCOREDIR}/3rdParty/libmdbx/lib/${COMPILER_CODE}/libmdbx.so)
endif()
