// SPDX-License-Identifier: LGPL-2.1-or-later OR GPL-2.0-or-later OR GPL-3.0-or-later OR LicenseRef-ImtCore-Commercial
#pragma once


// ACF includes
#include <ibase/TMakeModelObserverCompWrap.h>
#include <icomp/TModelCompWrap.h>
#include <icomp/TMakeComponentWrap.h>


// forward declarations
namespace imtservergql
{
class CHttpGraphQLServletComp;
class CGqlDemultiplexerComp;
class CGqlRepresentationDataControllerComp;
class CUserSettingsControllerComp;
class CGqlRepresentationJoinerComp;
class CApplicationInfoControllerComp;
class CSerializableObjectCollectionControllerComp;
class CGqlContextControllerComp;
class CObjectProviderComp;
class CWebSocketServletComp;
class CCollectionObjectProviderComp;
class COperationContextControllerComp;
class CObjectCollectionChangeNotifierComp;
class CModelChangeNotifierComp;
class CModelPublisherComp;
class CStructureSubscriberControllerComp;
class CBroadcastMessageConsumerControllerComp;
class CBroadcastMessageConsumerSubscriberComp;
class CSlaveSubscriberControllerComp;
class CGqlSearchControllerComp;
class CTableViewParamControllerComp;
class CConnectionStatusSubscriberControllerComp;
class CHeadersDataProviderComp;
class CDocumentRevisionControllerComp;
class CCommandsControllerComp;
class CSettingsControllerComp;
class CProgressManagerPublisherComp;
class CGqlCollectionImportControllerComp;
class CCollectionImportControllerComp;
class CCollectionImportJobParamsFillerComp;
class CCollectionDocumentServiceControllerComp;
class CCollectionDocumentServicePublisherComp;
class CPublisherSubscriberBridgeComp;
class CGqlContextCreatorComp;
class CFilterableSelectControllerComp;
class CUserGroupParamsSetJoinerComp;
} // namespace imtservergql


/**
	ImtServerGqlPck package
*/
namespace ImtServerGqlPck
{


typedef imtservergql::CHttpGraphQLServletComp GraphQLServlet;
typedef imtservergql::CWebSocketServletComp WebSocketServlet;
typedef imtservergql::CGqlDemultiplexerComp GraphQLDemultiplexer;
typedef imtservergql::CGqlRepresentationDataControllerComp GqlRepresentationDataController;
typedef imtservergql::CUserSettingsControllerComp UserSettingsController;
typedef imtservergql::CGqlRepresentationJoinerComp GqlRepresentationJoiner;
typedef imtservergql::CApplicationInfoControllerComp ApplicationInfoController;
typedef imtservergql::CGqlContextControllerComp GqlContextController;
typedef imtservergql::CObjectProviderComp ObjectProvider;
typedef imtservergql::CCollectionObjectProviderComp CollectionObjectProvider;
typedef imtservergql::CSerializableObjectCollectionControllerComp SerializableObjectCollectionController;
typedef imtservergql::COperationContextControllerComp OperationContextController;
typedef imtservergql::CObjectCollectionChangeNotifierComp ObjectCollectionChangeNotifier;
typedef imtservergql::CModelChangeNotifierComp ModelChangeNotifier;
typedef imtservergql::CModelPublisherComp ModelPublisher;
typedef imtservergql::CStructureSubscriberControllerComp StructureSubscriberController;
typedef imtservergql::CBroadcastMessageConsumerControllerComp BroadcastMessageConsumerController;
typedef imtservergql::CBroadcastMessageConsumerSubscriberComp BroadcastMessageConsumerSubscriber;
typedef imtservergql::CSlaveSubscriberControllerComp SlaveSubscriberController;
typedef imtservergql::CGqlSearchControllerComp GqlSearchController;
typedef imtservergql::CTableViewParamControllerComp TableViewParamController;
typedef imtservergql::CConnectionStatusSubscriberControllerComp ConnectionStatusSubscriberController;
typedef imtservergql::CHeadersDataProviderComp HeadersDataProvider;
typedef imtservergql::CDocumentRevisionControllerComp DocumentRevisionController;
typedef imtservergql::CCommandsControllerComp CommandsController;
typedef imtservergql::CSettingsControllerComp SettingsController;
typedef imtservergql::CProgressManagerPublisherComp ProgressManagerPublisher;
typedef imtservergql::CGqlCollectionImportControllerComp GqlCollectionImportController;
typedef imtservergql::CCollectionImportControllerComp CollectionImportController;
typedef imtservergql::CCollectionImportJobParamsFillerComp CollectionImportJobParamsFiller;
typedef imtservergql::CCollectionDocumentServiceControllerComp CollectionDocumentServiceController;
typedef imtservergql::CCollectionDocumentServicePublisherComp CollectionDocumentServicePublisher;
typedef imtservergql::CPublisherSubscriberBridgeComp PublisherSubscriberBridge;
typedef imtservergql::CGqlContextCreatorComp GqlContextCreator;
typedef imtservergql::CFilterableSelectControllerComp FilterableSelectController;
typedef imtservergql::CUserGroupParamsSetJoinerComp UserGroupParamsSetJoiner;


} // namespace ImtServerGqlPck

