import QtQuick 2.12
import imtguigql 1.0

/**
	\brief Base component for generated SDL operation types.

	\details Provides a unified execution state machine
	(\c idle | \c loading | \c success | \c error),
	a structured \l errorInfo object, and a typed \l result binding point.

	Generated subclasses (e.g. \c GetTicketRepresentationOperation) declare
	typed input properties and a typed \l result, then override \l execute()
	to prepare the input object and call \l _sendRequest().

	\note \c SdlOperation is a runtime-only base. All per-function code is
	generated by \c CQmlCodeOperationGeneratorComp; the internal transport
	reuses the existing \l GqlSdlRequestSender / \l GqlRequest stack
	unchanged, preserving full backward compatibility.

	Usage example:
	\code
	GetDocumentOperation {
		id: op
		m_id: documentId
		onSucceeded: console.log("id:", result.m_id, "name:", result.m_name)
		onFailed:    console.error("error:", errorInfo.message)
	}
	Button {
		text: "Load"
		onClicked: op.execute()
	}
	\endcode
*/
Item {
	id: root

	// -- State ------------------------------------------------------------------

	/// Current execution state: \c "idle" | \c "loading" | \c "success" | \c "error"
	readonly property string state: _state

	readonly property bool isLoading: _state === "loading"
	readonly property bool isSuccess: _state === "success"
	readonly property bool hasError:  _state === "error"

	// -- Error info -------------------------------------------------------------

	/**
		Structured error information. Non-null when \l hasError is true.

		Fields:
		\list
		\li \c message       {string}  — human-readable error message
		\li \c type          {string}  — error severity/category from GraphQL extensions
		\li \c httpStatus    {int}     — HTTP status code (0 when not available)
		\li \c commandId     {string}  — SDL function name that produced the error
		\li \c rawExtensions {var}     — raw GraphQL \c extensions object, or null
		\endlist
	*/
	readonly property var errorInfo: _errorInfo

	// -- Result -----------------------------------------------------------------

	/**
		Typed result object.

		Generated subclasses pre-allocate this property with the SDL output
		type instance, e.g.:
		\code
		result: TicketData {}
		\endcode
		When \l succeeded() fires the instance is populated in-place via
		\c fromObject(), so QML bindings to its fields remain valid.
	*/
	property var result: null

	// -- Configuration (set by generated subclass) ------------------------------

	property string gqlCommandId: ""

	/// 0 = Query, 1 = Mutation
	property int requestType: 0

	// -- Public API -------------------------------------------------------------

	/// Execute (or re-execute) the SDL operation.
	/// Override in generated subclass to populate the input object and call
	/// \l _sendRequest().
	function execute() {}

	/// Re-execute — alias for \l execute().
	function reload() { execute() }

	// -- Signals ----------------------------------------------------------------

	signal succeeded()
	signal failed(string message)

	// -- Internal state ---------------------------------------------------------

	property string _state: "idle"
	property var _errorInfo: null

	function _setState(newState) {
		if (_state !== newState) {
			_state = newState
		}
	}

	function _setSuccess() {
		_errorInfo = null
		_setState("success")
		root.succeeded()
	}

	function _setError(message, type, httpStatus, rawExtensions) {
		_errorInfo = {
			message:       message       || "",
			type:          type          || "Error",
			httpStatus:    httpStatus    || 0,
			commandId:     root.gqlCommandId,
			rawExtensions: rawExtensions || null
		}
		_setState("error")
		root.failed(message || "")
	}

	// -- Internal sender --------------------------------------------------------

	/// Call from \l execute() to dispatch the SDL request.
	function _sendRequest(inputObject) {
		_setState("loading")
		_senderImpl.send(inputObject)
	}

	GqlSdlRequestSender {
		id: _senderImpl
		gqlCommandId: root.gqlCommandId
		requestType:  root.requestType

		onStateChanged: {
			if (state === "Loading") {
				root._setState("loading")
			}
		}

		function onResult(data) {
			if (root.result) {
				root.result.fromObject(data)
			}
			root._setSuccess()
		}

		function onError(message, type) {
			root._setError(message, type, 0, null)
		}
	}
}
